name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  # push:
  #   branches:
  #     - main
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.nkns.cc/rss.xml"
          max_post_count: 10

      - name: Pull in Notes
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # ğŸ‘‡ è¿™é‡Œå¡«ä½ ç¬”è®°é¢‘é“çš„ RSS
          feed_list: "https://www.nkns.cc/notes/rss.xml"
          max_post_count: 10
          # ğŸ‘‡ å…³é”®ï¼å‘Šè¯‰å®ƒå»æ‰¾ "NOTES-LIST" è¿™ä¸ªé’©å­
          comment_tag_name: "NOTES-LIST"